"""empty message

Revision ID: 54885c16d669
Revises: 
Create Date: 2023-09-05 17:23:19.947282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54885c16d669'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
